```{r}
library("tidyverse") 
library("tidymodels")
library("glmnet")
library("GGally")
library("ggcorrplot")
library("MASS")
library("car")
library("lubridate")
library("lmtest")
library("splines")
```

```{r}
bike <- read_csv("bike_cleaned-3.csv")
```

```{r}
bike = bike %>% mutate(dteday = mdy(dteday))
bike = bike %>% mutate_if(is.character, as_factor)
bike = bike %>% mutate(hr = as_factor(hr))
```

```{r}
str(bike)
summary(bike)
#ggpairs(bike)
ggcorr(bike,label = TRUE,label_round = 2)
```
```{r}
ggplot(bike,aes(x=hr,y=count)) + geom_boxplot() + geom_jitter(alpha = 0.15) + theme_bw() + 
  theme(axis.text.x = element_text(angle = 90))

ggplot(bike,aes(x=season,y=count)) + geom_boxplot() + geom_jitter(alpha = 0.15) + theme_bw() + 
  theme(axis.text.x = element_text(angle = 90))

ggplot(bike,aes(x=mnth,y=count)) + geom_boxplot() + geom_jitter(alpha = 0.15) + theme_bw() + 
  theme(axis.text.x = element_text(angle = 90))

ggplot(bike,aes(x=holiday,y=count)) + geom_boxplot() + geom_jitter(alpha = 0.15) + theme_bw() + 
  theme(axis.text.x = element_text(angle = 90))

ggplot(bike,aes(x=weekday,y=count)) + geom_boxplot() + geom_jitter(alpha = 0.15) + theme_bw() + 
  theme(axis.text.x = element_text(angle = 90))
```
```{r}
bike_simple = recipe(count ~ hr, bike)
bike_simple
```

```{r}
lm_model = #give the model type a name 
  linear_reg() %>% #specify that we are doing linear regression
  set_engine("lm")
```

```{r}
lm_wflow = 
  workflow() %>% 
  add_model(lm_model) %>% 
  add_recipe(bike_simple)
```

```{r}
lm_fit = fit(lm_wflow, bike)
```

```{r}
summary(lm_fit$fit$fit$fit)
```

```{r}
ggplot(bike,aes(x=temp,y=count)) + geom_point(alpha=0.1) + geom_smooth(method = "lm", color = "red") + theme_bw()
```

Multi
```{r}
bike2_recipe = recipe(count ~ hr + temp, bike)

lm_model = #give the model type a name 
  linear_reg() %>% #specify that we are doing linear regression
  set_engine("lm") #specify the specify type of linear tool we want to use 

lm_wflow = 
  workflow() %>% 
  add_model(lm_model) %>% 
  add_recipe(bike2_recipe)

lm_fit2 = fit(lm_wflow, bike)

summary(lm_fit2$fit$fit$fit)
```

```{r}
summary(lm_fit2$fit$fit$fit)
```
```{r}
bike3_recipe = recipe(count ~ atemp + temp, bike)

lm_model = #give the model type a name 
  linear_reg() %>% #specify that we are doing linear regression
  set_engine("lm") #specify the specify type of linear tool we want to use 

lm_wflow = 
  workflow() %>% 
  add_model(lm_model) %>% 
  add_recipe(bike3_recipe)

lm_fit3 = fit(lm_wflow, bike)

summary(lm_fit3$fit$fit$fit)
```
```{r}
bike2 <- bike %>% dplyr::select("season", "mnth", "hr", "holiday", "weekday", "workingday", "weathersit",
"temp", "atemp", "hum", "windspeed", "count")
```


```{r}
bike2
```


```{r}
allmod = lm(count ~., bike2) #use the ~. to include all predictors rather than typing them all in
summary(allmod)
```

```{r}
#backward
backmod = stepAIC(allmod, direction = "backward", trace = TRUE) #trace = TRUE shows how the model is built (which variables are removed)
summary(backmod)
```

